[package]
name = "rust_todoapp_adeel"
version = "0.1.0"
authors = ["adeilh <madeel234@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = "0.17.5"
openssl = "0.10.30"
postgres-openssl = "0.3.0"
